# Generated by Django 4.2 on 2024-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
